image: node:stretch-slim

stages:
    - prepublish
    - publish

codeclimate:
    stage: prepublish
    script:
        - npm install
        - npm run lint
        - npm run test
        - npm run covupload

upload:
    stage: publish
    dependencies:
        - codeclimate
    only:
        - tags
    script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish