image: node:stretch-slim

stages:
    - setup
    - prepublish
    - publish

cache:
    paths:
        - node_modules/

install:
    stage: setup
    script:
        - npm install

codeclimate:lint:
    stage: prepublish
    dependencies:
        - install
    script:
        - npm run lint

codeclimate:lint:
    stage: prepublish
    dependencies:
        - install
    script:
        - npm run test

codeclimate:lint:
    stage: prepublish
    dependencies:
        - install
    script:
        - npm run covupload

upload:
    stage: publish
    dependencies:
        - codeclimate
    only:
        - tags
    script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish